FROM debian:jessie-slim

RUN apt-get update -q && apt-get install -yq \
	libboost-iostreams1.55.0 \
	libboost-system1.55.0 \
	libgmp10 \
	liblua5.2 \
	libluajit-5.1 \
	libmysqlclient18 \
	libpugixml1

WORKDIR /build
