FROM debian:jessie-slim

RUN apt-get update && apt-get install -y \
	cmake \
  g++ \
  make \
  libboost-iostreams-dev \
  libboost-system-dev \
	libgmp-dev \
  libluajit-5.1-dev \
  libmysqlclient-dev \
	libpugixml-dev

WORKDIR /build
# CMD ["sh", "-c", "cmake /source && make -j2"]

# vim: set et sw=2 ts=2 syntax=dockerfile:
