name: Check code style

permissions:
  contents: read

on:
  push:
    branches:
      - dev
      - v*

    paths:
      - .clang-format
      - .github/workflows/clang-format.yml
      - src/**

  pull_request:
    paths:
      - .clang-format
      - .github/workflows/clang-format.yml
      - src/**

  workflow_dispatch:

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup LLVM repository
        run: |
          source /etc/os-release
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/llvm.gpg > /dev/null
          sudo echo "deb [signed-by=/usr/share/keyrings/llvm.gpg] http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-21 main" | sudo tee /etc/apt/sources.list.d/llvm.list

      - name: Install dependencies
        run: sudo apt-get update -yqq && sudo apt-get install -yqq clang-format-21

      - name: Check code style
        run: clang-format-21 -n -style=file --Werror src/*.{cpp,h}
